name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          pre-commit install-hooks

      - name: Run linters (pre-commit)
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run tests
        run: python -m pytest -q

      - name: Run benchmark
        run: python bench/bench.py

      - name: Build Docker image
        run: docker build -t neuron/base:ci -f Dockerfile .
