name: Terraform Plan

on:
  pull_request:
    paths: ["infra/terraform/**"]
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply changes? (true to apply)"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: us-east-1
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform -chdir=infra/terraform fmt -check

      - name: Terraform Init
        run: terraform -chdir=infra/terraform init -backend=false

      - name: Terraform Plan
        run: terraform -chdir=infra/terraform plan -lock=false -var="project_prefix=neuron-mvp"

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' && inputs.apply == 'true'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform -chdir=infra/terraform apply -auto-approve -lock=false -var="project_prefix=neuron-mvp"
